'use client'

import { useEffect, useMemo, useState } from 'react'
import { Bell, CalendarDays, Check, ChevronLeft, ChevronRight, CirclePlus, Clock3, CreditCard, Edit3, Home, MoreHorizontal, Plus, ReceiptText, Settings2, Trash2, X } from 'lucide-react'
import { formatDate, formatShortDate, Loan, money, paid, progress, remaining, schedule, daysLeft, uid } from '@/lib/debt'

type View = 'home' | 'calendar' | 'reminders' | 'detail' | 'form' | 'payment'
const colorMap = { blue: 'loan-blue', orange: 'loan-orange', violet: 'loan-violet', red: 'loan-red' }

export default function DebtTracker() {
  const [loans, setLoans] = useState<Loan[]>([])
  const [hydrated, setHydrated] = useState(false)
  const [view, setView] = useState<View>('home')
  const [selected, setSelected] = useState<string | null>(null)
  const [editing, setEditing] = useState<Loan | null>(null)
  const [notice, setNotice] = useState('')
  useEffect(() => { const saved = localStorage.getItem('debt-tracker-loans'); if (saved) { try { setLoans(JSON.parse(saved)) } catch { localStorage.removeItem('debt-tracker-loans') } } setHydrated(true) }, [])
  useEffect(() => { if (hydrated) localStorage.setItem('debt-tracker-loans', JSON.stringify(loans)) }, [loans, hydrated])
  useEffect(() => { if ('Notification' in window && Notification.permission === 'default') Notification.requestPermission().catch(() => {}) }, [])
  const active = loans.find(l => l.id === selected) || null
  const total = loans.reduce((s, l) => s + remaining(l), 0)
  const totalPaid = loans.reduce((s, l) => s + paid(l), 0)
  const totalDebt = loans.reduce((s, l) => s + l.total, 0)
  const urgent = loans.filter(l => daysLeft(l.dueDate) <= 14 && remaining(l) > 0)
  const open = (next: View, loan?: Loan) => { if (loan) setSelected(loan.id); setView(next) }
  const saveLoan = (loan: Loan) => { setLoans(current => current.some(l => l.id === loan.id) ? current.map(l => l.id === loan.id ? loan : l) : [...current, loan]); setView('home'); setNotice('Loan saved'); setTimeout(() => setNotice(''), 2500) }
  const addPayment = (amount: number, date: string, note: string) => { if (!active) return; setLoans(current => current.map(l => l.id === active.id ? { ...l, payments: [...l.payments, { id: uid(), amount, date, note }] } : l)); setView('detail'); setNotice('Payment logged — nice work'); setTimeout(() => setNotice(''), 2500) }
  const removeLoan = () => { if (!active) return; setLoans(current => current.filter(l => l.id !== active.id)); setView('home') }
  return <div className="app-shell">
    <header className="topbar"><div><p className="eyebrow">PERSONAL FINANCE / 2026</p><h1>Debt, <span>handled.</span></h1></div><button className="icon-button" aria-label="Notifications" onClick={() => open('reminders')}><Bell size={19}/>{urgent.length > 0 && <i/>}</button></header>
    {notice && <div className="toast"><Check size={16}/> {notice}</div>}
    {urgent.length > 0 && view === 'home' && <button className="alert-banner" onClick={() => open('reminders')}><span className="alert-mark">!</span><span><strong>{urgent.length} payment{urgent.length > 1 ? 's' : ''} need attention</strong><small>{urgent[0].lender} is due {daysLeft(urgent[0].dueDate) < 0 ? 'overdue' : `in ${daysLeft(urgent[0].dueDate)} days`}</small></span><ChevronRight size={18}/></button>}
    {view === 'home' && <HomeView loans={loans} total={total} totalPaid={totalPaid} totalDebt={totalDebt} open={open}/>} 
    {view === 'calendar' && <CalendarView loans={loans}/>} 
    {view === 'reminders' && <RemindersView loans={loans} open={open}/>} 
    {view === 'detail' && active && <DetailView loan={active} open={open} onDelete={removeLoan}/>} 
    {view === 'payment' && active && <PaymentForm loan={active} onCancel={() => setView('detail')} onSave={addPayment}/>} 
    {view === 'form' && <LoanForm loan={editing} onCancel={() => setView('home')} onSave={saveLoan}/>} 
    {view !== 'form' && view !== 'payment' && <nav className="tabbar"><button className={view === 'home' || view === 'detail' ? 'active' : ''} onClick={() => setView('home')}><Home size={19}/><span>Home</span></button><button className={view === 'calendar' ? 'active' : ''} onClick={() => setView('calendar')}><CalendarDays size={19}/><span>Calendar</span></button><button className={view === 'reminders' ? 'active' : ''} onClick={() => setView('reminders')}><Bell size={19}/><span>Reminders{urgent.length > 0 && <b>{urgent.length}</b>}</span></button></nav>}
  </div>
}

function HomeView({ loans, total, totalPaid, totalDebt, open }: { loans: Loan[]; total: number; totalPaid: number; totalDebt: number; open: (v: View, l?: Loan) => void }) {
  const sorted = [...loans].sort((a, b) => a.dueDate.localeCompare(b.dueDate)); const percent = totalDebt ? Math.round(totalPaid / totalDebt * 100) : 0
  return <main className="content"><section className="hero-grid"><div className="total-panel"><div className="panel-kicker">REMAINING DEBT <span>● LIVE</span></div><strong>{money(total)}</strong><p>across {loans.length} active loans</p><div className="total-footer"><div className="mini-progress"><i style={{ width: `${percent}%` }}/></div><small>{percent}% paid down</small></div></div><div className="ring-panel"><div className="ring" style={{ '--progress': `${percent * 3.6}deg` } as React.CSSProperties}><div><strong>{percent}%</strong><small>paid</small></div></div><span>Momentum<br/><b>is building.</b></span></div></section><div className="section-heading"><div><p className="eyebrow">YOUR LOANS</p><h2>Keep it moving.</h2></div><button className="add-button" onClick={() => open('form')}><Plus size={17}/> Add loan</button></div><section className="loan-list">{sorted.map(loan => <LoanCard key={loan.id} loan={loan} onClick={() => open('detail', loan)}/>)}</section>{loans.length === 0 && <EmptyState onClick={() => open('form')}/>}</main>
}
function LoanCard({ loan, onClick }: { loan: Loan; onClick: () => void }) { const left = daysLeft(loan.dueDate); const isUrgent = left <= 14; return <button className={`loan-card ${colorMap[loan.color]}`} onClick={onClick}><div className="loan-card-top"><span className="lender-icon"><CreditCard size={18}/></span><span className="loan-lender">{loan.lender}<small>{loan.notes || 'Personal loan'}</small></span><MoreHorizontal size={18}/></div><div className="loan-card-mid"><div><small>STILL TO PAY</small><strong>{money(remaining(loan))}</strong></div><span className={isUrgent ? 'due-badge urgent' : 'due-badge'}>{left < 0 ? 'OVERDUE' : `${left} DAYS LEFT`}</span></div><div className="loan-card-bottom"><div className="progress-track"><i style={{ width: `${progress(loan)}%` }}/></div><span>{progress(loan)}% paid</span><span>Due {formatShortDate(loan.dueDate)}</span></div></button> }
function EmptyState({ onClick }: { onClick: () => void }) { return <div className="empty"><ReceiptText size={30}/><h3>Nothing hanging over you.</h3><p>Add your first loan to get a clear plan.</p><button className="primary-button" onClick={onClick}>Add a loan</button></div> }

function DetailView({ loan, open, onDelete }: { loan: Loan; open: (v: View, l?: Loan) => void; onDelete: () => void }) { const rows = schedule(loan); return <main className="content detail-page"><button className="back-button" onClick={() => open('home')}><ChevronLeft size={18}/> All loans</button><div className={`detail-hero ${colorMap[loan.color]}`}><div className="loan-card-top"><span className="lender-icon"><CreditCard size={18}/></span><span className="loan-lender">{loan.lender}<small>{loan.notes || 'Personal loan'}</small></span><button className="ghost-icon" aria-label="Edit loan" onClick={() => open('form', loan)}><Edit3 size={16}/></button></div><p className="detail-label">REMAINING</p><strong className="detail-amount">{money(remaining(loan))}</strong><div className="detail-stats"><span><small>Borrowed</small>{money(loan.borrowed)}</span><span><small>Total repay</small>{money(loan.total)}</span><span><small>Paid</small>{money(paid(loan))}</span></div></div><button className="primary-button wide" onClick={() => open('payment', loan)}><CirclePlus size={18}/> Log a payment</button><section className="detail-section"><div className="section-heading compact"><div><p className="eyebrow">PAYOFF PLAN</p><h2>One step at a time.</h2></div><span className="pill">{loan.payoffMode === 'even' ? 'Even split' : 'Fixed amount'}</span></div><div className="schedule">{rows.slice(0, 5).map(row => <div className="schedule-row" key={row.date}><span className="date-dot"/><span><b>{formatDate(row.date)}</b><small>planned payment</small></span><strong>{money(row.amount)}</strong><small>{money(row.after)} left</small></div>)}</div></section><section className="detail-section"><div className="section-heading compact"><div><p className="eyebrow">PAYMENT HISTORY</p><h2>Receipts so far.</h2></div></div>{loan.payments.length ? loan.payments.slice().reverse().map(p => <div className="history-row" key={p.id}><span><b>{formatDate(p.date)}</b><small>{p.note || 'Payment recorded'}</small></span><strong>−{money(p.amount)}</strong></div>) : <p className="muted">No payments logged yet.</p>}</section><button className="delete-button" onClick={onDelete}><Trash2 size={16}/> Delete this loan</button></main> }

function CalendarView({ loans }: { loans: Loan[] }) { const rows = loans.flatMap(l => schedule(l).map(r => ({ ...r, lender: l.lender }))).sort((a, b) => a.date.localeCompare(b.date)); const grouped = rows.reduce<Record<string, typeof rows>>((a, r) => { const key = r.date.slice(0, 7); (a[key] ||= []).push(r); return a }, {}); return <main className="content"><div className="page-title"><p className="eyebrow">PLAN AHEAD</p><h2>Calendar</h2><p>Every planned payment, in one place.</p></div><div className="month-strip"><button aria-label="Previous month"><ChevronLeft size={18}/></button><strong>{new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric' }).format(new Date())}</strong><button aria-label="Next month"><ChevronRight size={18}/></button></div>{Object.entries(grouped).slice(0, 3).map(([month, items]) => <section className="calendar-month" key={month}><div className="month-heading"><b>{new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric' }).format(new Date(month + '-15'))}</b><span>{money(items.reduce((s, x) => s + x.amount, 0))} planned</span></div>{items.map((r, i) => <div className="calendar-row" key={`${r.date}-${i}`}><span className="calendar-date"><b>{new Date(r.date + 'T12:00:00').getDate()}</b><small>{new Intl.DateTimeFormat('en-US', { weekday: 'short' }).format(new Date(r.date + 'T12:00:00'))}</small></span><span><b>{r.lender}</b><small>Balance after: {money(r.after)}</small></span><strong>{money(r.amount)}</strong></div>)}</section>)}</main> }
function RemindersView({ loans, open }: { loans: Loan[]; open: (v: View, l?: Loan) => void }) { return <main className="content"><div className="page-title"><p className="eyebrow">DON&apos;T MISS A BEAT</p><h2>Reminders</h2><p>Quiet nudges, right when you need them.</p></div><div className="permission-card"><span className="permission-icon"><Bell size={20}/></span><div><b>Device notifications</b><small>Alerts are shown here even when notifications are off.</small></div><span className="toggle on"><i/></span></div><section className="reminder-list"><p className="eyebrow">UPCOMING</p>{loans.sort((a, b) => a.dueDate.localeCompare(b.dueDate)).map(l => <button className="reminder-row" key={l.id} onClick={() => open('detail', l)}><span className={`reminder-date ${colorMap[l.color]}`}><Clock3 size={16}/><b>{Math.max(0, daysLeft(l.dueDate) - (Number.parseInt(l.reminder) || 0))}</b><small>DAYS</small></span><span><b>{l.lender}</b><small>{l.reminder} · due {formatShortDate(l.dueDate)}</small></span><ChevronRight size={17}/></button>)}</section></main> }

function LoanForm({ loan, onCancel, onSave }: { loan: Loan | null; onCancel: () => void; onSave: (l: Loan) => void }) { const [form, setForm] = useState<Loan>(loan || { id: uid(), lender: '', notes: '', borrowed: 0, total: 0, dueDate: '', reminder: '7 days before', payoffMode: 'even', period: 'monthly', payments: [], color: 'blue' }); const set = (key: keyof Loan, value: string | number) => setForm({ ...form, [key]: value }); return <main className="content form-page"><button className="back-button" onClick={onCancel}><X size={18}/> Cancel</button><div className="page-title"><p className="eyebrow">{loan ? 'UPDATE LOAN' : 'NEW LOAN'}</p><h2>{loan ? 'Edit the details.' : 'Make a plan.'}</h2><p>The clearer it is, the lighter it feels.</p></div><div className="form-card"><label>Lender or app<input value={form.lender} onChange={e => set('lender', e.target.value)} placeholder="e.g. Klarna"/></label><label>What was it for?<input value={form.notes} onChange={e => set('notes', e.target.value)} placeholder="Optional note"/></label><div className="form-two"><label>Amount borrowed<input type="number" value={form.borrowed || ''} onChange={e => set('borrowed', Number(e.target.value))}/></label><label>Total to repay<input type="number" value={form.total || ''} onChange={e => set('total', Number(e.target.value))}/></label></div><label>Due date<input type="date" value={form.dueDate} onChange={e => set('dueDate', e.target.value)}/></label><label>Reminder timing<select value={form.reminder} onChange={e => set('reminder', e.target.value)}>{['Same day', '1 day before', '3 days before', '7 days before', '14 days before', '30 days before'].map(x => <option key={x}>{x}</option>)}</select></label><label>Payoff mode<select value={form.payoffMode} onChange={e => set('payoffMode', e.target.value as Loan['payoffMode'])}><option value="even">Even split by date</option><option value="fixed">Fixed payment amount</option></select></label><label>How much are you paying each month?<div className="money-input"><span>₹</span><input type="number" min="1" value={form.fixedAmount || ''} onChange={e => set('fixedAmount', Number(e.target.value))} placeholder="0"/></div></label><button className="primary-button wide" disabled={!form.lender || !form.total || !form.dueDate} onClick={() => onSave(form)}>{loan ? 'Save changes' : 'Add loan'} <ChevronRight size={18}/></button></div></main> }
function PaymentForm({ loan, onCancel, onSave }: { loan: Loan; onCancel: () => void; onSave: (a: number, d: string, n: string) => void }) { const [amount, setAmount] = useState(''); const [date, setDate] = useState(new Date().toISOString().slice(0, 10)); const [note, setNote] = useState(''); return <main className="content form-page"><button className="back-button" onClick={onCancel}><ChevronLeft size={18}/> {loan.lender}</button><div className="page-title"><p className="eyebrow">RECORD PROGRESS</p><h2>Log a payment.</h2><p>{money(remaining(loan))} still to pay on {loan.lender}.</p></div><div className="form-card"><label>Payment amount<div className="money-input"><span>₹</span><input autoFocus type="number" value={amount} onChange={e => setAmount(e.target.value)} placeholder="0"/></div></label><label>Date<input type="date" value={date} onChange={e => setDate(e.target.value)}/></label><label>Note <span className="optional">optional</span><input value={note} onChange={e => setNote(e.target.value)} placeholder="e.g. July payment"/></label><button className="primary-button wide" disabled={!Number(amount)} onClick={() => onSave(Number(amount), date, note)}>Save payment <Check size={18}/></button></div></main> }
